<?php

include_once 'library/config.php';

$redis = new TwitterRedis(REDIS_SERVER);

$categories = [
	'politics' => [
		"Absentee", "Accountable", "Activist", "Adverse", "Advertising", "Advice", "Advise", "Affiliation", "Aggressive", "Amendment", "Announcement", "Anthem", "Appeal", "Appearance", "Appoint", "Approach", "Appropriation", "Arguments", "Articulate", "Aspiration", "Asset", "Assimilation", "At large", "Audience", "Authorization",
"Background", "Bait", "Balanced budget", "Ballot", "Ballot box", "Bandwagon", "Barnstorm", "Behavior", "Beliefs", "Biannual", "Bias", "Bicameral", "Bill", "Bipartisan", "Boondoggle", "Brochure", "Budget", "Bunk", "Bureaucracy",
"Cabinet", "Campaign", "Candidate", "Canvass", "Capitalize", "Career", "Catalyst", "Caucus", "Ceiling", "Centrist", "Challenge", "Challenger", "Changes", "Charismatic", "Checks and balances", "Choice", "Citation", "Civic", "Coalition", "Coast-to-coast", "Coattail", "Collaboration", "Colleague", "Collective", "Commitments", "Committee", "Commonality", "Communication", "Compassion", "Concede", "Concessions", "Confidence", "Congress", "Congressional", "Conscience", "Consequence", "Conservative", "Constituent", "Constitution", "Consultation", "Contribution", "Controversy", "Convene", "Convention", "Council", "Curiosity", "Cycle",
"Dark horse", "Debate", "Decision", "Decisive", "Declaration", "Defeat", "Deficit", "Delegate", "Deliberate", "Deliberation", "Democracy", "Democrat", "Democratic", "Derision", "Destiny", "Diligent", "Diplomat", "Disapproval", "Discourse", "Discreet", "Discussion", "Disheartened", "Dishonesty", "Dissatisfaction", "District", "Distrust", "Diverse", "Division", "Dogma", "Dominate", "Donation", "Donor", "Dossier", "Dynamic",
"Effective", "Efficient", "Elation", "Electoral college", "Elevate", "Eloquence", "Emphasis", "Enact", "Endorsement", "Engaging", "Equal", "Ethics", "Euphoria", "Excessive", "Executive", "Exit poll", "Experience",
"Faction", "Federal", "Feud", "Filibuster", "Flawed", "Focus", "Forum", "Fraud", "Freedom", "Front runner", "Fundamental", "Funding", "Fundraiser",
"Gambit", "Gerrymander", "Glaring", "GOP", "Government", "Grass roots", "Grateful",
"Handshakes", "Hard money", "Hatch Act", "Heckle", "Historic", "Honesty", "Hooray", "Hypocrisy",
"Immigrants", "Impound", "Inalienable", "Incentive", "Incorporate", "Incumbency", "Incumbent", "Independent", "Independent", "Indulge", "Infallible", "Influx", "Informative", "Initiative", "Innuendo", "Inspiring", "Integrity", "Interests", "Investigate", "Involvement", "Irresponsible", "Issues",
"Jeopardy", "JUBILANT", "Judge", "Judicial",
"Keen", "Knowledge",
"Lame duck", "Landslide", "Law", "Leader", "Leadership", "Leanings", "Legal", "Legalization", "Legislature", "Liberal", "Listening", "Lobbyist", "Lone", "Loser", "Loss", "Loyalty",
"Magistrate", "Majority", "Mandate", "Meaningful", "Measures", "Media", "Meetings", "Mentor", "Midterm election", "Minority", "Misinformation", "Motives", "Mudslinging",
"National", "Nationwide", "Negativity", "Network", "Nominate", "Nominee", "Nonpartisan",
"Obligation", "Obsequious", "Offensive", "Office", "Official", "Old boy", "Opine", "Opinion", "Opinionated", "Opportunity", "Opposition", "Orator(y)", "Outspoken", "Ovation",
"PAC", "Pamphlets", "Pardon", "Participation", "Partisanship", "Party", "Patriotism", "Petition", "Platform", "Pledge", "Plurality", "Polarize", "Policy", "Polite", "Politician", "Politics", "Poll", "Polling place", "Pollster", "Popular", "Popularity", "Pork barrel", "Position paper", "Pragmatist", "Praise", "Precinct", "Predictions", "Prescient", "Press", "Pride", "Primary", "Priority", "Proactive", "Process", "Progressive", "Projection", "Promises", "Propaganda", "Proponent", "Proposal", "Purpose",
"Query", "Quest", "Questions", "Quorum", "Quotes",
"Race", "Ratify", "Re-election", "Reapportionment", "Recall", "Recognition", "Reconciliation", "Recount", "Recrimination", "Redistrict", "Referendum", "Reform", "Registration", "Regulate", "Representation", "Republican", "Rescind", "Resignation", "Resilience", "Restrictions", "Retort", "Reveal", "Revelations", "Revenues", "Rhetoric", "Roll call", "Runoff",
"Scope", "Senate", "Seniority", "Shift", "Shortcoming", "Shuffle", "Sidelines", "Sinecure", "Skill", "Slate", "Slogan", "Solicitation", "Solution", "Spar", "Spectacle", "Speculate", "Spending", "Spin", "Stakes", "Stance", "State's rights", "Statute", "Strategist", "Strategy", "Straw poll", "Stump", "Subcommittee", "Subjects", "Success", "Suffrage", "Support", "System",
"Tactics", "Tally", "Taxpayer", "Term", "Term limit", "Ticket", "Topic", "Trust", "Turnout",
"Ultimate", "Unanimous", "Uncommitted", "Unfair", "Uniformity", "Unity", "Unknown", "Unopposed", "Unprecedented", "Unwind", "Upcoming", "Upset",
"Vacancy", "Veto", "Viable", "Victor", "Victory", "Vie", "Viewpoint", "Views", "Violations", "VIP", "Volunteers", "Voter", "Vulnerability",
"Ward", "Whistle-stop", "Wild-card", "Win", "Winner", "Withdraw", "Withhold", "Woo",
"Xenophobic",
"Yell", "Yield",
"Zeal", "Zealous", "Zone"
	],
	'barbecue' => [
		"All day", "Apple pie", "Aroma",
		"Baked beans", "Band", "Barbecue", "Bash", "Beans", "Beautiful", "Beer", "Blast", "Blueberries", "Boys", "Bring", "Brunch", "Burgers",
		"Cake", "Casual", "Celebration", "Checkered tablecloths", "Cherries", "Chicken", "Children", "Chili", "Chips", "Choices", "Coleslaw", "Congenial", "Conversation", "Cookies", "Cooking", "Cool", "Cooperate", "Corn on the cob", "Crowded", "Crying",
		"Dessert", "Deviled eggs", "Dinner", "Dip", "Drinks",
		"Eating", "Effort", "Embellish", "Entertain",
		"Family", "Fire", "Food", "Forks", "Friends", "Friendships", "Fruit",
		"Games", "Garnish", "Gathering", "Girls", "Greetings", "Grill", "Group", "Guacamole",
		"Hamburgers", "Hospitality", "Hot", "Hot dogs", "Hugs", "Humid", "Hunger", "Hungry",
		"Ice cream", "Ice cream cones", "Ice-tea", "Interaction", "Invitation",
		"Jeans", "Join", "Joy",
		"Ketchup", "Kin", "Kindness", "Kiss", "Knives",
		"Laughter", "Lemonade", "Loitering", "Lollipops", "Lunch",
		"Men", "Music",
		"Nature", "Neighborhood", "Noise",
		"Occasion", "Odor", "Onions", "Open pit", "Outdoors", "Overwhelming",
		"Paper plates", "Park", "Pasta salad", "Patio", "Peaches", "Pears", "Pepper", "Pickles", "Pies", "Plums", "Pop", "Popsicles", "Porch", "Pork", "Pot luck", "Potato salad", "Preparation", "Pulled pork",
		"Quantity",
		"Regularity", "Relatives", "Ribs", "Rolls", "Running",
		"Salads", "Salsa", "Salt", "Sandwiches", "Sauce", "Sauce", "Sausages", "Seafood", "Select", "Servings", "Settings", "Shorts", "Slices", "Smell", "Soda", "Spoons", "Spring", "Steaks", "Stories", "Strawberries", "Summer", "Swimming",
		"Tables", "Tales", "Teens", "Temperature", "Tomatoes", "Tradition",
		"Unique", "Universal",
		"Vacation", "Vegetables",
		"Watermelon", "Weather", "Weekends", "Wieners", "Willing", "Wine", "Women", "Work",
		"Yard", "Year-round"
	],
	'happy' => [
		"absolutely",
		"adorable",
		"accepted",
		"acclaimed",
		"accomplish",
		"accomplishment",
		"achievement",
		"action",
		"active",
		"admire",
		"adventure",
		"affirmative",
		"affluent",
		"agree",
		"agreeable",
		"amazing",
		"angelic",
		"appealing",
		"approve",
		"aptitude",
		"attractive",
		"awesome",
		"beaming",
		"beautiful",
		"believe",
		"beneficial",
		"bliss",
		"bountiful",
		"bounty",
		"brave",
		"bravo",
		"brilliant",
		"bubbly",
		"calm",
		"celebrated",
		"certain",
		"champ",
		"champion",
		"charming",
		"cheery",
		"choice",
		"classic",
		"classical",
		"clean",
		"commend",
		"composed",
		"congratulation",
		"constant",
		"cool",
		"courageous",
		"creative",
		"cute",
		"dazzling",
		"delight",
		"delightful",
		"distinguished",
		"divine",
		"earnest",
		"easy",
		"ecstatic",
		"effective",
		"effervescent",
		"efficient",
		"effortless",
		"electrifying",
		"elegant",
		"enchanting",
		"encouraging",
		"endorsed",
		"energetic",
		"energized",
		"engaging",
		"enthusiastic",
		"essential",
		"esteemed",
		"ethical",
		"excellent",
		"exciting",
		"exquisite",
		"fabulous",
		"fair",
		"familiar",
		"famous",
		"fantastic",
		"favorable",
		"fetching",
		"fine",
		"fitting",
		"flourishing",
		"fortunate",
		"free",
		"fresh",
		"friendly",
		"fun",
		"funny",
		"generous",
		"genius",
		"genuine",
		"giving",
		"glamorous",
		"glowing",
		"good",
		"gorgeous",
		"graceful",
		"great",
		"green",
		"grin",
		"growing",
		"handsome",
		"happy",
		"harmonious",
		"healing",
		"healthy",
		"hearty",
		"heavenly",
		"honest",
		"honorable",
		"honored",
		"hug",
		"idea",
		"ideal",
		"imaginative",
		"imagine",
		"impressive",
		"independent",
		"innovate",
		"innovative",
		"instant",
		"instantaneous",
		"instinctive",
		"intuitive",
		"intellectual",
		"intelligent",
		"inventive",
		"jovial",
		"joy",
		"jubilant",
		"keen",
		"kind",
		"knowing",
		"knowledgeable",
		"laugh",
		"legendary",
		"light",
		"learned",
		"lively",
		"lovely",
		"lucid",
		"lucky",
		"luminous",
		"marvelous",
		"masterful",
		"meaningful",
		"merit",
		"meritorious",
		"miraculous",
		"motivating",
		"moving",
		"natural",
		"nice",
		"novel",
		"now",
		"nurturing",
		"nutritious",
		"okay",
		"one",
		"one-hundred percent",
		"open",
		"optimistic",
		"paradise",
		"perfect",
		"phenomenal",
		"pleasurable",
		"plentiful",
		"pleasant",
		"poised",
		"polished",
		"popular",
		"positive",
		"powerful",
		"prepared",
		"pretty",
		"principled",
		"productive",
		"progress",
		"prominent",
		"protected",
		"proud",
		"quality",
		"quick",
		"quiet",
		"ready",
		"reassuring",
		"refined",
		"refreshing",
		"rejoice",
		"reliable",
		"remarkable",
		"resounding",
		"respected",
		"restored",
		"reward",
		"rewarding",
		"right",
		"robust",
		"safe",
		"satisfactory",
		"secure",
		"seemly",
		"simple",
		"skilled",
		"skillful",
		"smile",
		"soulful",
		"sparkling",
		"special",
		"spirited",
		"spiritual",
		"stirring",
		"stupendous",
		"stunning",
		"success",
		"successful",
		"sunny",
		"super",
		"superb",
		"supporting",
		"surprising",
		"terrific",
		"thorough",
		"thrilling",
		"thriving",
		"tops",
		"tranquil",
		"transforming",
		"transformative",
		"trusting",
		"truthful",
		"unreal",
		"unwavering",
		"up",
		"upbeat",
		"upright",
		"upstanding",
		"valued",
		"vibrant",
		"victorious",
		"victory",
		"vigorous",
		"virtuous",
		"vital",
		"vivacious",
		"wealthy",
		"welcome",
		"well",
		"whole",
		"wholesome",
		"willing",
		"wonderful",
		"wondrous",
		"worthy",
		"wow",
		"yes",
		"yummy",
		"zeal",
		"zealous",
	],
	'sad' => [
		"Ability", "Abnormal", "Abuse", "Adolescents", "Affect", "Agency", "Aid", "Alarm", "Alienation", "All ages", "Alone", "Anger", "Anguish", "Antidepressant", "Anxiety", "Anxious", "Attempt", "Attention", "Attitude", "Awareness",
		"Bipolar", "Blase", "Blue", "Brain",
		"Caregiver", "Certify", "Child", "Clarity", "Clinical", "Communication", "Concern", "Conclude", "Condition", "Confide", "Confusion", "Cooperative", "Cope", "Counsel", "Courage", "Cruel", "Cure", "Cycle",
		"Data", "Death", "Debilitating", "Defeated", "Degree", "Depressed", "Depression", "Descent", "Despair", "Detriment", "Diagnosis", "Die", "Discrimination", "Disease", "Disinterest", "Disorder", "Disorder", "Distracted", "Doctor", "Dog days", "Down", "Drugs",
		"Education", "Effect", "Endure", "Esteem", "Evaluation",
		"Family", "Fatigued", "Fear", "Feelings", "Fight", "Finality", "Friends",
		"Gain", "Grief", "Grieving", "Guideline",
		"Hard work", "Heal", "Health", "Help", "Helpless", "Hereditary", "Hopelessness", "Hot-line", "Hurt",
		"Immune", "Improvement", "Inability", "Inactivity", "Indicator", "Insecure", "Interested", "Interfere", "Involvement", "Irritable", "Isolation", "Issues",
		"Jeer", "Joking",
		"Kill", "Knowledge", "Knowledgeable",
		"Label", "Lack", "Level", "Level", "Listening",
		"Media", "Medication", "Medicine", "Melancholia", "Mental", "Mental health", "Misunderstanding", "Monitor",
		"Necessary", "Need", "Negative", "Normal", "Nothing",
		"Observation", "Oncoming", "Opinion", "Option", "Organize", "Overcome", "Overwhelmed",
		"Pain", "Panic", "Parents", "Patience", "Patient", "Pattern", "Pay attention", "Peers", "Personal", "Physician", "Pills", "Prescription", "Prevent", "Prevention", "Programs", "Progress", "Progressive", "Protect", "Psychiatrist",
		"Quality", "Quantity", "Query", "Quest",
		"Reality", "Report", "Requirement", "Resulting", "Review",
		"Sadness", "Scared", "Security", "Separation", "Seriousness", "Siblings", "Signs", "Skills", "Sleep", "Sleep pattern", "Solitary", "Sorrow", "Source", "Statistics", "Stigma", "Strength", "Struggle", "Studies", "Substance abuse", "Succor", "Suffer", "Suicide", "Sympathetic", "Symptoms",
		"Tack", "Talk", "Talking", "Teenagers", "Tentative", "Terrified", "Therapy", "Thoughts", "Time", "Tired", "Tragedy", "Tragic", "Trajectory", "Treat", "Treatment", "Treatment", "Treatment", "Triumph", "Troubled",
		"Uncertain", "Uncomfortable", "Understanding", "Unfulfilled", "Unique", "Unsettling", "Unusual",
		"Validation", "Victim",
		"Warning", "Watch", "Withdrawal", "World Health Organization", "Worry", "Worthless",
		"Youth",
		"Zero",
	]
];

foreach ($categories as $category => $words) {
	foreach ($words as $word) {
		$redis->addOrIncrCategoryMember($category, $word);
	}
}
